name: Build with bob

on:
  pull_request:
  push:
    branches: main

env:
  VERSION_FILENAME: "info.json"
  BUILD_SERVER: "https://build.defold.com"

jobs:
  build_with_bob:
    strategy:
      matrix:
        platform: [armv7-android, x86_64-linux, x86_64-win32, js-web]
    runs-on: ubuntu-latest

    name: Build
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Get Defold version
        run: |
          TMPVAR=`curl -s http://d.defold.com/stable/${{env.VERSION_FILENAME}} | jq -r '.sha1'`
          echo "DEFOLD_VERSION=${TMPVAR}" >> $GITHUB_ENV
          echo "Found version ${TMPVAR}"

      - name: Download bob.jar
        run: |
          wget -q http://d.defold.com/archive/stable/${{env.DEFOLD_VERSION}}/bob/bob.jar
          java -jar bob.jar --version

      - name: Resolve libraries
        run: java -jar bob.jar resolve --email a@b.com --auth 123456
      - name: Build
        run: java -jar bob.jar --platform=${{ matrix.platform }} build --archive --build-server=${{env.BUILD_SERVER}}
      - name: Bundle
        run: java -jar bob.jar --platform=${{ matrix.platform }} bundle

  build_with_bob_macos:
    strategy:
      matrix:
        platform: [x86_64-ios, x86_64-macos]
    runs-on: macOS-latest

    name: Build
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Get Defold version
        run: |
          TMPVAR=`curl -s http://d.defold.com/stable/${{env.VERSION_FILENAME}} | jq -r '.sha1'`
          echo "DEFOLD_VERSION=${TMPVAR}" >> $GITHUB_ENV
          echo "Found version ${TMPVAR}"

      - name: Download bob.jar
        run: |
          wget -q http://d.defold.com/archive/stable/${{env.DEFOLD_VERSION}}/bob/bob.jar
          java -jar bob.jar --version

      - name: Resolve libraries
        run: java -jar bob.jar resolve --email a@b.com --auth 123456
      - name: Build
        run: java -jar bob.jar --platform=${{ matrix.platform }} build --archive --build-server=${{env.BUILD_SERVER}}
      - name: Bundle
        run: java -jar bob.jar --platform=${{ matrix.platform }} bundle
